//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ACME.Module.BusinessObjects.bdACME
{

    public partial class AplicacionServicios : XPLiteObject
    {
        long fId;
        [Key]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        string fNombreAplicacion;
        public string NombreAplicacion
        {
            get { return fNombreAplicacion; }
            set { SetPropertyValue<string>("NombreAplicacion", ref fNombreAplicacion, value); }
        }
        Usuarios fIdUsuarios;
        [Association(@"AplicacionServiciosReferencesUsuarios")]
        public Usuarios IdUsuarios
        {
            get { return fIdUsuarios; }
            set { SetPropertyValue<Usuarios>("IdUsuarios", ref fIdUsuarios, value); }
        }
        Gerencias fIdGerencias;
        [Association(@"AplicacionServiciosReferencesGerencias")]
        public Gerencias IdGerencias
        {
            get { return fIdGerencias; }
            set { SetPropertyValue<Gerencias>("IdGerencias", ref fIdGerencias, value); }
        }
        Periodos fIdPeriodos;
        [Association(@"AplicacionServiciosReferencesPeriodos")]
        public Periodos IdPeriodos
        {
            get { return fIdPeriodos; }
            set { SetPropertyValue<Periodos>("IdPeriodos", ref fIdPeriodos, value); }
        }
        Servicios fIdServicios;
        [Association(@"AplicacionServiciosReferencesServicios")]
        public Servicios IdServicios
        {
            get { return fIdServicios; }
            set { SetPropertyValue<Servicios>("IdServicios", ref fIdServicios, value); }
        }
        Oficinas fIdOficinas;
        [Association(@"AplicacionServiciosReferencesOficinas")]
        public Oficinas IdOficinas
        {
            get { return fIdOficinas; }
            set { SetPropertyValue<Oficinas>("IdOficinas", ref fIdOficinas, value); }
        }
    }

}
