//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ACME.Module.BusinessObjects.bdACME
{

    public partial class Gerencias : XPLiteObject
    {
        long fId;
        [Key]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        string fNombreGerencia;
        [Size(30)]
        public string NombreGerencia
        {
            get { return fNombreGerencia; }
            set { SetPropertyValue<string>("NombreGerencia", ref fNombreGerencia, value); }
        }
        [Association(@"AplicacionServiciosReferencesGerencias")]
        public XPCollection<AplicacionServicios> AplicacionServiciosCollection { get { return GetCollection<AplicacionServicios>("AplicacionServiciosCollection"); } }
    }

}
