//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ACME.Module.BusinessObjects.bdACME
{

    public partial class Oficinas : XPLiteObject
    {
        long fId;
        [Key]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        string fNombreOficina;
        [Size(40)]
        public string NombreOficina
        {
            get { return fNombreOficina; }
            set { SetPropertyValue<string>("NombreOficina", ref fNombreOficina, value); }
        }
        [Association(@"AplicacionServiciosReferencesOficinas")]
        public XPCollection<AplicacionServicios> AplicacionServiciosCollection { get { return GetCollection<AplicacionServicios>("AplicacionServiciosCollection"); } }
    }

}
