//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ACME.Module.BusinessObjects.bdACME
{

    public partial class Usuarios : XPLiteObject
    {
        long fId;
        [Key]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        string fAgencia;
        [Size(30)]
        public string Agencia
        {
            get { return fAgencia; }
            set { SetPropertyValue<string>("Agencia", ref fAgencia, value); }
        }
        string fNroUsuarios;
        [Size(30)]
        public string NroUsuarios
        {
            get { return fNroUsuarios; }
            set { SetPropertyValue<string>("NroUsuarios", ref fNroUsuarios, value); }
        }
        Departamentos fIdDepartamento;
        [Association(@"UsuariosReferencesDepartamentos")]
        public Departamentos IdDepartamento
        {
            get { return fIdDepartamento; }
            set { SetPropertyValue<Departamentos>("IdDepartamento", ref fIdDepartamento, value); }
        }
        [Association(@"AplicacionServiciosReferencesUsuarios")]
        public XPCollection<AplicacionServicios> AplicacionServiciosCollection { get { return GetCollection<AplicacionServicios>("AplicacionServiciosCollection"); } }
    }

}
